spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/oims_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123$}

jwt.secret=${JWT_SECRET:kfeiu3q298jkjnsw983jsahdfin90jks}
jwt.expiration=${JWT_EXPIRATION:3600000}
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health
MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always